Address Bundler's deprecation messages
* This fixes the following deprecations:

    [DEPRECATED] Using the `config` command without a subcommand [list, get, set, unset] is deprecated and will be removed in the future.
    Use `bundle config set --global path .bundle` instead.

* Removes a redundant `--global` option:

    ERROR: "bundle config get" was called with arguments ["--global", "path"]